### ISSUE TITLE
UpdateCustomReward() gives BadTokenException

### ISSUE THREAD

**Issue by Chris-Is-Awesome** [TwitchLib/TwitchLib.Api#287]
```csharp
await helix.ChannelPoints.UpdateCustomReward(userId, rewardId, request, token);
```
That always returns the error "The token provided in the request did not match the associated user. Make sure the token you're using is from the resource owner (streamer? viewer?)" even though I've verified the data I'm passing it is correct.

Doing some research, I came across posts from last year saying the error reporting here can be inaccurate, not sure if that's been fixed since mid last year? So not sure if this error is even giving me the right info.

Tried updating from 3.3 to 3.4 and that didn't fix it, so I'm sure it's either something I'm missing or maybe I need to install a prerelease?

**Comment by Mahsaap** [comment]
Can't fix what is returned in the API. Sadly it's limited on what Twitch returns hense the general response.
Pre-release will be the same. 

Did you create a custom Reward with the same token and Id? (Token generated from that account)
Do other calls work? Other calls that are broadcaster only? (Get broadcaster subscriptions for example.)
Do you have affiliate / partner on the account your attempting this on?
Is the token and the user ID the broadcaster?

Proper auth flow is a must on Helix and if a generator is used, you will likely not get passed this wall.

As for version I'm assuming your talking about the suite because the API is now 3.6 as of a couple days ago. 3.4 should be the latest and pre release will not work on the the suite. You will need to install them individually to try that.

**Comment by Mahsaap** [comment]
also these are required parameter pairs to set max per stream, max per user per stream, and global cooldown.

**Comment by Chris-Is-Awesome** [comment]
> Did you create a custom Reward with the same token and Id? (Token generated from that account) You can only update Rewards you have generated with the API. Do other calls work?

Oh that's the issue then, the reward I was trying to update wasn't created with the bot.

As for your other questions, other get calls work, this was my first time trying a post call. Was trying this on my channel which is affiliate, and the token & user are mine, and the same as what I've used in other requests without issue.

And yeah, I was referring to the suite version, but good to know that what's returned from the API isn't changeable, thanks for the info!

**Comment by Mahsaap** [comment]
I believe this has been sovled.
