### ISSUE TITLE
Bad Resource Exception on Follower Service

### ISSUE THREAD

**Issue by xDeveluxe** [TwitchLib/TwitchLib.Api#344]
Hello.
For some reason Im receiving an exception:
TwitchLib.Api.Core.Exceptions.BadResourceException: The resource you tried to access was not valid.

Thats happening under Follower Service:
![image](https://user-images.githubusercontent.com/102395107/221187936-740b66df-5c95-4cd1-b951-b4176fdc37d0.png)

Cant find any reason for that to happen.
API Access token, client id, client secret is right and working well (other calls like request user follower data and etc).
What can be wrong?

**Comment by Syzuna** [comment]
Twitch deprecated their old follow endpoints and only older client ids can use it.
The Follower Service was not updated to use the new follow endpoints yet so that might be the cause.
If you can try to use EventSub for real time notifications (websocket if you are making a desktop app or webhooks if your app runs on a server with a valid domain and ssl certificate)

**Comment by xDeveluxe** [comment]
Thank you for the information, didnt found it anywhere else. 
Will try to setup EventSub then.
